# Generated by Django 4.2.20 on 2025-04-09 13:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('rating_kp', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка кинопоиска')),
                ('release_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1985)], verbose_name='Год выпуска')),
            ],
        ),
    ]
